### ISSUE TITLE
No compatible file selected

### ISSUE THREAD

**Issue by 1405100494** [Tilapiatsu/blender-Universal_Multi_Importer#1]
I try to import compatible files, but all operations show this information, I use Blender 4.0.2 (also 4.1) and 2.0.0 plugin, I don't understand why this is, is it a Bug?
There is only one recursive depth option in the page options for importing folders, and no matter what value I set, it doesn't work.

**Comment by Tilapiatsu** [comment]
If I understand correctly you used the `Import Folder` operator as you have the recursion depth in th import options. So you need to pick a folder which contains at least one compatible file. you can find the list in th GitHub page.

I have no issue on my side.
It's a bit hard to help you with the information you gave me. Can you explain a bit more in detail what your are doing, and what files are in the folder you try to import ?

**Comment by 1405100494** [comment]
I imported a test folder with three subfolders containing fbx files. Using the built-in fbx and another option, it is possible to display and import files normally. But using the import folder, fbx is not recognized in the directory, and it will be displayed no matter what you do. Here is the video.

https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/assets/72635400/921ab746-92b2-4adf-9556-b62e4a8c841d

**Comment by 1405100494** [comment]
> If I understand correctly you used the `Import Folder` operator as you have the recursion depth in th import options. So you need to pick a folder which contains at least one compatible file. you can find the list in th GitHub page.
> 
> I have no issue on my side. It's a bit hard to help you with the information you gave me. Can you explain a bit more in detail what your are doing, and what files are in the folder you try to import ?
Is there any difference between your import folder operation and what I demonstrated in the video？

**Comment by Tilapiatsu** [comment]
It's indeed really weird. Everything looks correct. I'll try to send you a version which will give me more info about what's happening behind the hood.
I'll keep you posted :)

**Comment by 1405100494** [comment]
I see. Thanks!

**Comment by Tilapiatsu** [comment]
Hi @1405100494 

Here is a version that will output more info to the logfile for me to better understand what's going on. So in order to try it properly, can you :

- Uninstall previous version
- Install this new version
- retry to import a folder hierarchy -> you should see new messages on the 3d Viewport, But will also save a .log file located in -> `%temp%` folder with a name `UMI_XXXXXXX.log` 
- Send the log file to me

Thanks a lot !

[universal_multi_importer_logging_filepath.zip](https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/files/14881261/universal_multi_importer_logging_filepath.zip)

**Comment by 1405100494** [comment]
Strangely, after I installed this, I could import it normally, and after I tried to install 2.0.2 again, I could also use it normally. I will try to test this on my computer at home after work to see what the difference is. At the earliest, this problem appeared on my computer at home, and another batch script that called FBX plug-in to import did not work.
If the computer at home can also import smoothly, I think it may be caused by a plug-in conflict, which solved the problem without my knowledge (close or delete).
The test result will be replied to you later, thank you!

**Comment by 1405100494** [comment]
I think I've found the problem, and it's probably fbx, which happens when I import these specific skeleton mesh bodies fbx.
Maybe you can test it out with these files and they will look like the ones demonstrated in the video. And when this happens, using the above plugin leaves no logs.
[test.zip](https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/files/14896961/test.zip)

**Comment by Tilapiatsu** [comment]
Ohhhh it's actually a bug :D 

The issue comes from the Capial case of the extensions `.FBX`
It's my bad ! 

I'm preparing a quick fix and keep you posted .

Thanks again for the report

**Comment by 1405100494** [comment]
It can work now!
Thanks for your hardworking!

**Comment by Tilapiatsu** [comment]
That's awesome! Thanks for your time ☺️
Closing the issue
