### ISSUE TITLE
Enable is error

### ISSUE THREAD

**Issue by mac4kent** [Tilapiatsu/blender-Universal_Multi_Importer#2]
Extension install button is error see picture on Blender.app 4.2.0
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/48278e91-7178-4b28-8f4b-8aa2cd7240c9">

This for MacOS Ventura 13.6.7

**Comment by Tilapiatsu** [comment]
Good Evening @mac4kent !

Thank you for reaching out.

Indeed I don't have a Mac so I've never tried on this OS.
If you can give me more info I can try to help and fix the issue.

Here is a build which will print more info in the terminal. if you can :
* remove previous addon
* install this modify addon

In the terminal you should see 3 lines after enabling the addon

UMI : Log file will be saved in : C:\path\to\temp\folder\XXXXXXXX
UMI : Temp Folder :  C:\path\to\temp\folde
UMI : Log file path :  C:\path\to\temp\folder\XXXXXXXXUMI_XXXXXXXXX.log

If you can send me what those line are it would help me 

[universal_multi_importer_printlog.zip](https://github.com/user-attachments/files/16228837/universal_multi_importer_printlog.zip)

**Comment by mac4kent** [comment]
Yes I will show you my screen record tomorrow during our son go school

**Comment by mac4kent** [comment]
There for Mac path.
https://youtu.be/IoHeZCFTZ9E
You can put /tmp/ on show from hidden folder.
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/0941a3e5-781a-4e4b-99d1-046431f47626">
Also you can ask question to Nutti (Screencast Key) about Windows, Macintosh, and Linux is 3 separate path.

https://github.com/nutti/Screencast-Keys

if mac {
Macintosh
} elseif windows {
Windows
} else if Linux {
Linux
}

**Comment by mac4kent** [comment]
https://youtu.be/avttMp-Qrr0

You may read my comment youtube.

**Comment by Tilapiatsu** [comment]
Thanks a lot @mac4kent for these info and videos :) but I would really need you to install the modified addon I've send you. 
I'm using a standardize way of accessing tempfolder which should work on any platform ( PC, Linux, Mac) ... but apparently it is not entirely the case.
So I need to understand what path is outputed from this tempfolder method.
Maybe the path is wrong, or maybe there is actually a file access issue.

Thanks in advance

**Comment by mac4kent** [comment]
I already test there same version and still fail.

**Comment by mac4kent** [comment]
Oh really I show you my Blender 4.2.0
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/4636f883-917b-42b9-9402-f1f65d969213">

**Comment by mac4kent** [comment]
This one youtube. https://youtu.be/RbQCzk-ef3g

**Comment by Tilapiatsu** [comment]
> This one youtube. https://youtu.be/RbQCzk-ef3g

This is great ! did you tried to 
* right click on the blender app -> show package contents
* browse to content/MacOs
* to drag and drop the blender exec into the terminal to run it
* then enable the addon

**Comment by mac4kent** [comment]
'NoneType' object has no attribute 'umi_colors'
UMI : Creating Preset Folder : /Users/kentdavis/Library/Application Support/Blender/4.2/scripts/presets/umi/command_batcher

**Comment by mac4kent** [comment]
[Kent on MacOS 1.0.0.txt](https://github.com/user-attachments/files/16233053/Kent.on.MacOS.1.0.0.txt)

**Comment by Tilapiatsu** [comment]
> [Kent on MacOS 1.0.0.txt](https://github.com/user-attachments/files/16233053/Kent.on.MacOS.1.0.0.txt)
Thanks a lot for your time :)

Great ! We're moving forward !
Apparently my modification isn't catching the issue properly. so I've made other changes. Can you retry with this V2 ?

[universal_multi_importer_printlog_v2.zip](https://github.com/user-attachments/files/16233571/universal_multi_importer_printlog_v2.zip)

I'm sorry I know it might be tedious for you, but because I don't have a Mac this is the only way I have to help you out

**Comment by mac4kent** [comment]
Same problem.

**Comment by Tilapiatsu** [comment]
don't you have other things printed in the console ?

**Comment by mac4kent** [comment]
How?

**Comment by Tilapiatsu** [comment]
> > This one youtube. https://youtu.be/RbQCzk-ef3g
> 
> This is great ! did you tried to
> 
> * right click on the blender app -> show package contents
> * browse to content/MacOs
> * to drag and drop the blender exec into the terminal to run it
> * then enable the addon and look in the terminal

I mean follow the same steps but with the V2 
https://github.com/user-attachments/files/16233571/universal_multi_importer_printlog_v2.zip

And give send me the complete console print like you did here :


> [Kent on MacOS 1.0.0.txt](https://github.com/user-attachments/files/16233053/Kent.on.MacOS.1.0.0.txt)

**Comment by mac4kent** [comment]
[Kent on MacOS 1.0.1.txt](https://github.com/user-attachments/files/16237005/Kent.on.MacOS.1.0.1.txt)

**Comment by Tilapiatsu** [comment]
Thanks !
This time the console caught the proper path.

I finally made some changes that would fix the issue you had. Please let me know if it works properly now. If it is good i'll make a proper release with the fix.

[universal_multi_importer_newlog.zip](https://github.com/user-attachments/files/16240407/universal_multi_importer_newlog.zip)

**Comment by mac4kent** [comment]
Yaaaaa ay it worked.
<img width="3000" alt="image" src="https://github.com/user-attachments/assets/2341a6f9-5663-4ade-943d-c8e4227de7ea">

and

<img width="3000" alt="image" src="https://github.com/user-attachments/assets/d01375d6-fc87-45ce-a933-b3d5f287f255">

**Comment by mac4kent** [comment]
Don't forget update new version 2.1.4 or whatever you want.

**Comment by Tilapiatsu** [comment]
That's awesome !
Thanks for the confirmation :) I'll make a proper release on Github but it will arrive later on [extensions.blender.org](https://extensions.blender.org/) as the validation process is a bit longer.

Thanks again for your time :)

**Comment by Tilapiatsu** [comment]
https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/releases/tag/v2.1.4

**Comment by Tilapiatsu** [comment]
it is also available in https://extensions.blender.org/add-ons/universal-multi-importer/ if you prefer to get it that way :).
There is only an approval the first time I upload, but not after each update

**Comment by mac4kent** [comment]
sure you are welcome
