### ISSUE TITLE
OBJ Scale is always 0

### ISSUE THREAD

**Issue by Thane5** [Tilapiatsu/blender-Universal_Multi_Importer#5]
I am importing a bunch of OBJ files, and the meshes always appear to be invisible because their scale is 0. It also seems that the "scale" setting on the importer has no effect on this.

**Comment by Tilapiatsu** [comment]
Hi @Thane5 !

Thanks for reaching out. I've tryed to import Obj and didn't got any issue ...

Can you give me more info about your OS ( Windows, Linux or MacOS ), The version of Blender and the addon you are running.
It would help me better understand the issue.

I guess you have already check that the scale import settings for OBJ is at 1.0 ?

![image](https://github.com/user-attachments/assets/623acb95-f951-417b-986a-aab11a51582b)

If it is not private, and you can share the culprit obj? I would be able to reproduce the issue myself and debug it if necessary.

**Comment by Thane5** [comment]
Well, thats weird. Tried to replicate this case with the same files as last time, and the scale was fine.
