### ISSUE TITLE
Add-On Freezes Blender 4.2 After Importing

### ISSUE THREAD

**Issue by dPeaceKeepr** [Tilapiatsu/blender-Universal_Multi_Importer#6]
Hi Tilapiatsu,

I used the addon to try to import around 400 .usd files and the addon does import them all as the on screen log shows "Batch Import completed sucessfully!" but as soon as it finishes, it freezes Blender completely. Even if I wait for 5-10 mins, its still completely frozen.

Could you please check this out and release a patch. Would greatly help the community.

Also Thankyou for the great addon. Makes importing multiple files easier compared to default importer.

Thanks

**Comment by dPeaceKeepr** [comment]
I also tried import 3 .usd files, still no success.

**Comment by Tilapiatsu** [comment]
Hi @dPeaceKeepr!

Thanks for reaching out.
The "freeze" of the screen is intended in some way, It allows the user to inspect the log, by `ctrl` + `scroll` to see if there was any issue during a long import.
You can press `esc` to hide the log and take control over blender again. There is a text on the bottom right corner of the 3d View to show you the shortcuts available :

![image](https://github.com/user-attachments/assets/dc5edde0-1938-4397-b929-0c624e423ee2)

If you don't like this behaviour you can Auto hide the log at the end of each import in the global importer settings, after selecting the files in the browser.

![image](https://github.com/user-attachments/assets/a9714382-d97c-4ee8-9c50-580bac3b036b)

Please let me know if it helped ?

**Comment by dPeaceKeepr** [comment]
Thanks. Worked Like a charm.
