### ISSUE TITLE
Import module update with more ui widgets

### ISSUE THREAD

**Issue by Hombre57** [Tilapiatsu/blender-Universal_Multi_Importer#7]
Hi @Tilapiatsu ,

This is not an issue but a question.

I've proposed a PR to solve [issue 12](https://projects.blender.org/extensions/io_scene_x3d/issues/12) of the x3D import module, with more options. As of now, I don't see the new widgets in your extension.

Can I do something to integrate the change in some configuration files or are you supposed to survey and integrate any change yourself? Sorry if that's already explained somewhere, I just haven't found that information.

**Comment by Tilapiatsu** [comment]
Hi @Hombre57 

I'm sorry, I let you so long without answer. I was not focus on this addon. Thanks for reaching out.

I'm currently updating my addon to be ready for the release of 4.3. And  I've updated the settings for x3D
This is how it currently look :
![image](https://github.com/user-attachments/assets/a6055135-b349-4d1a-b463-f71bfbafa429)

It is still in the develop branch but I'll make a proper release soon.
https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/archive/refs/heads/develop.zip
Feel free to try it out and let me know if you have any feedback.
Thanks

**Comment by Tilapiatsu** [comment]
Oh and by the way I didn't showed the `Import as collection` because my addon is already handleing that and it would create double collection
![image](https://github.com/user-attachments/assets/7de2d72b-544b-4982-bf71-ec7ddfdd7c8c)

**Comment by Hombre57** [comment]
Hi @Tilapiatsu,

Thanks for looking into it before 4.3 is out 😉

I replaced the content of `AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\universal_multi_importer` by the content of your archive and restarted Blender. Unfortunately, I don't see the additional widgets. The standalone X3D import menu entry is working fine. Did I missed something ? Does it work for all languages (French here) ?

**Comment by Tilapiatsu** [comment]
Je suis francais également 😄 

Je ne suis pas sûr que cette façon de faire soit la meilleur, et aussi, je n'ai jamais tester avec Blender en Francais, mais je ne penses pas que ca soit le problème.

Plutôt que de remplacer le contenu de l'extension, pourriez vous desinstaller l'extension, redémarer puis installer cette version comme un addon classique : 
[universal_multi_importer_2.1.6.zip](https://github.com/user-attachments/files/17788292/universal_multi_importer_2.1.6.zip)
En passant par cette fonction :
![image](https://github.com/user-attachments/assets/ddb4aa74-b037-4878-a545-c2a0f07b6655)

Si tout s'est bien passé, vous devriez avoir les settings suivants
![image](https://github.com/user-attachments/assets/bb3337b2-861f-4042-a745-577b84cd0391)

Si les settings ne sont pas visible, pouvez vous vérifier dans le `system console` pour voir si vous avez des erreurs ?

**Comment by Hombre57** [comment]
Bonjour @Tilapiatsu,

Add-on installé via la procédure que tu m'as décrite, mais toujours pas de widget supplémentaire 😞 

![UMI-01](https://github.com/user-attachments/assets/b4c1103e-87ef-42e1-b556-5e0c23747d5f)

Je teste sous Blender 4.2.3, est-ce censé être compatible ? Je n'ai pas de quoi compiler Blender, je ne m'occupe que de quelques scripts Python...

Peut-être plus grave, j'ai lancé l'import de 2 fichier WRL : il s'est passé sans problème, sauf que Blender est gelé ! J'ai pu appuyer sur ESC pour faire disparaître ton overlay (comme c'était écrit), mais c'est toujours gelé. Ci-dessous le log de la console :

```
TBBmalloc: skip allocation functions replacement in ucrtbase.dll: unknown prologue for function _msize
UMI : Log file path : C:\Users\JEAN-C~1\AppData\Local\Temp\UMI_20241117.log
'NoneType' object has no attribute 'umi_colors'
bpy.ops.import_scene.dxf not found
bpy.ops.import_scene.max not found
bpy.ops.import_mesh.pdb not found
bpy.ops.import_scene.embroidery not found
bpy.ops.import_mesh.xyz not found
UMI : create class from operator bpy.ops.wm.alembic_import
UMI : create class from operator bpy.ops.import_scene.tila_import_blend
UMI : create class from operator bpy.ops.import_anim.bvh
UMI : create class from operator bpy.ops.wm.collada_import
UMI : create class from operator bpy.ops.import_scene.fbx
UMI : create class from operator bpy.ops.import_scene.gltf
UMI : create class from operator bpy.ops.image.import_as_mesh_planes
UMI : create class from operator bpy.ops.image.open
UMI : create class from operator bpy.ops.object.empty_image_add
UMI : create class from operator bpy.ops.wm.obj_import
UMI : create class from operator bpy.ops.wm.ply_import
UMI : create class from operator bpy.ops.wm.stl_import
UMI : create class from operator bpy.ops.import_curve.svg
UMI : create class from operator bpy.ops.wm.usd_import
UMI : create class from operator bpy.ops.import_scene.x3d
Avertissement: 1 × Draw window and swap : 43.7815 ms, moyenne : 43.78149999 ms
Avertissement: 1 × Draw window and swap : 4.5286 ms, moyenne : 4.52859999 ms
Avertissement: 1 × Draw window and swap : 37.2962 ms, moyenne : 37.29620000 ms
Avertissement: 1 × Draw window and swap : 37.5725 ms, moyenne : 37.57250000 ms
```
[UMI_20241117.log](https://github.com/user-attachments/files/17790154/UMI_20241117.log)

**Comment by Tilapiatsu** [comment]
Merci pour ton retour!

Je pensais que vous etiez sur la 4.3, et je ne pensais pas que les settings étaient dur la 4.2 aussi.

[universal_multi_importer_2.1.6.zip](https://github.com/user-attachments/files/17791065/universal_multi_importer_2.1.6.zip)

Ca devrait fonctionner Maintenant :)

**Comment by Hombre57** [comment]
Je pense qu'on peut se tutoyer, oui ;)

Nouvelle archive installé, je vois bien les widgets supplémentaire, mais l'import échoue, voir log ci-joint. Je ne sais pas s'il est utile de passer du temps à déboguer cet add-on sur la V4.2 si elle a déjà été testé sur la V4.3. Je te laisse décider de poursuivre ce test en 4.2 ou pas, je reste à ta disposition.

[Import.log](https://github.com/user-attachments/files/17792479/Import.log)
[UMI_20241117.log](https://github.com/user-attachments/files/17792481/UMI_20241117.log)

**Comment by Tilapiatsu** [comment]
Oui on peut se tutoyer ca sera plus simple :p 
Je suis désolé pour tout ses allez retours. Chez moi tout fonctionne correctement ... en voyant tes logs il semblerai qu'un paramètre `solidify` n'ai pas été enregistré correctement.

Pourrais tu vérifier que l'addon X3d soit a jour? Si c'cest pas le cas, il devrai avoir un bouton `update` a peu près ici
![image](https://github.com/user-attachments/assets/48d7e620-8a1b-4e78-9d7c-6b0197781b20)
La version courante est la version 2.4.1

La 2eme chose serai de desactiver Universal multi importer, redémarer blender, réactivier l'addon et verifier le log

Tu devrais pouvoir verifier que tout soit ok dans les préférences de l'addon en cliquand sur ce bouton
![image](https://github.com/user-attachments/assets/6ee1302e-07ae-45c2-bba4-30bb5285dda4)

Merci beaucoup pour ton temps

**Comment by Tilapiatsu** [comment]
Et j'ai d'ailleurs release une update, qui n'a pas d'impacte sur ton problème, mais ca ne mangera pas de pain de la prendre
https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/releases/download/v2.1.7/universal_multi_importer_2.1.7.zip

**Comment by Hombre57** [comment]
Effectivement, le module d'import X3D n'était pas à jour. Add-on 2.1.7 installé et testé avec succès ! 👍 Merci pour les infos.

Il se peut que de nouvelles options apparaissent dans cette interface d'import. Je créerais un nouveau ticket lorsque nécessaire.

Je te laisse fermer le ticket.

**Comment by Tilapiatsu** [comment]
Super ! Merci pour la confirmation :)
De mon coté, je vais faire le nécessaire pour exposer le problème a l'utilisateur, en vérifiant la version de l'addon et en le proposant de mettre a jour si nécessaire, pour éviter les erreurs comme tu a eu.
Tu disais également que de nouvelles option pourrai apparaitre ? Ou est-ce que tu te renseigne pour avoir l'info?
Il faut aussi que je me tienne au courant pour anticiper correctement.

**Comment by Hombre57** [comment]
Disons que j'aimerais ajouter quelques fonctionnalités supplémentaires tel que la fusion de corps (de faces) et la factorisation des textures pour éviter les duplicatas, c'est à l'étude mais rien de concret pour le moment. Cela ne représenterait que 2 cases à cocher.

**Comment by Tilapiatsu** [comment]
ok merci je vois.
J'ai suivi cette page, je pense que je recevrais des notifications en cas de changement sur le module d'import
https://projects.blender.org/extensions/io_scene_x3d
Merci beaucoup pour ton aide.

Je me permet de fermer ce ticket, et n'hésite pas a en ouvrir un autre en cas de besoin

Bonne journée a toi :)
