### ISSUE TITLE
[feature request] skip duplicated mesh's files

### ISSUE THREAD

**Issue by abasgames** [Tilapiatsu/blender-Universal_Multi_Importer#8]
the title self-explanatory 

possible way implement
add a toogle to
check all files checksum against each other 
if a match found then only load one and skip all the others

**Comment by Tilapiatsu** [comment]
Hi @abasgames.

Sorry for letting you so long without answer. I was not focus on this addon.

Thanks for reaching out, it is a pretty interesting feature and I've just coded a proposal for what you have suggested

![image](https://github.com/user-attachments/assets/e8298ef3-9de7-4b7d-9187-c418147ba3fb)

After selecting files or folder in the first windows, you can tick or untick duplicated file.
Depending on the number and the size of the files in the list, it can take quite some time to calculate and compare Checksum. By consequence, the checksum is only calculated and kept in memory the first time you click on these buttons. And if you click a second time it will be faster
It is still in the develop branch for now but I'm planning to make a proper release soon.

https://github.com/Tilapiatsu/blender-Universal_Multi_Importer/archive/refs/heads/develop.zip

If you have time, I would apreciate to hear you feedback about it after you have tried it ?

Cheers

**Comment by Tilapiatsu** [comment]
Closing the issue, if you still have issue, you can open a new one please
